SELECT A.PRODUCT_ID,A.PRODUCT_NAME,SUM(A.PRICE * O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT A JOIN FOOD_ORDER O
ON A.PRODUCT_ID = O.PRODUCT_ID
WHERE SUBSTRING(O.PRODUCE_DATE,6,2) = '05'
GROUP BY A.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC;