# SELECT H.HISTORY_ID,
#         (CASE WHEN DATEDIFF(H.END_DATE,H.START_DATE)+1 < 7 THEN ROUND(C.DAILY_FEE * (DATEDIFF(H.END_DATE,H.START_DATE)+1)) 
#          WHEN DATEDIFF(H.END_DATE,H.START_DATE)+1 < 30 THEN ROUND(C.DAILY_FEE * 0.95 * (DATEDIFF(H.END_DATE,H.START_DATE)+1))
#         WHEN DATEDIFF(H.END_DATE,H.START_DATE)+1 < 90 THEN ROUND(C.DAILY_FEE * 0.93 * (DATEDIFF(H.END_DATE,H.START_DATE)+1))
#         WHEN DATEDIFF(H.END_DATE,H.START_DATE)+1 >= 90 THEN ROUND(C.DAILY_FEE * 0.9 * (DATEDIFF(H.END_DATE,H.START_DATE)+1))
#         END) AS 'FEE'
# FROM CAR_RENTAL_COMPANY_CAR C 
# JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
# ON C.CAR_ID = H.CAR_ID 
# JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
# ON C.CAR_TYPE = P.CAR_TYPE
# WHERE C.CAR_TYPE = '트럭'
# GROUP BY H.HISTORY_ID
# ORDER BY FEE DESC, H.HISTORY_ID DESC

SELECT HISTORY_ID, 
    round(DAILY_FEE * (DATEDIFF(h.END_DATE,h.START_DATE)+1)
    * (case 
    when DATEDIFF(END_DATE,START_DATE)+1 < 7 then 1
    when DATEDIFF(END_DATE,START_DATE)+1 < 30 then 0.95
    when DATEDIFF(END_DATE,START_DATE)+1 < 90 then 0.92
    else 0.85 end)) as "FEE"

from CAR_RENTAL_COMPANY_CAR as c 
    join CAR_RENTAL_COMPANY_RENTAL_HISTORY as h
    on c.CAR_ID = h.CAR_ID
    join CAR_RENTAL_COMPANY_DISCOUNT_PLAN as p
    on c.CAR_TYPE = p.CAR_TYPE

where c.car_type = "트럭"

group by HISTORY_ID

order by FEE desc , HISTORY_ID desc