SELECT F.PRODUCT_ID, F.PRODUCT_NAME, F.PRICE * SUM(O.AMOUNT) AS TOTAL_SALES
# SELECT *
FROM FOOD_PRODUCT F JOIN FOOD_ORDER O ON F.PRODUCT_ID = O.PRODUCT_ID
WHERE DATE_FORMAT(O.PRODUCE_DATE,"%Y-%m") = '2022-05'
GROUP BY F.PRODUCT_ID
ORDER BY F.PRICE * SUM(O.AMOUNT) DESC, F.PRODUCT_ID ASC
